/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "rscp.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(rscp_Acknowledge, rscp_Acknowledge, AUTO)


PB_BIND(rscp_GPSCoordinate, rscp_GPSCoordinate, AUTO)


PB_BIND(rscp_BatteryState, rscp_BatteryState, AUTO)


PB_BIND(rscp_ArmDisarm, rscp_ArmDisarm, AUTO)


PB_BIND(rscp_NavigateToGPS, rscp_NavigateToGPS, AUTO)


PB_BIND(rscp_SearchArea, rscp_SearchArea, AUTO)


PB_BIND(rscp_SetStage, rscp_SetStage, AUTO)


PB_BIND(rscp_StartExploration, rscp_StartExploration, AUTO)


PB_BIND(rscp_RequestEnvelope, rscp_RequestEnvelope, AUTO)


PB_BIND(rscp_TaskFinished, rscp_TaskFinished, AUTO)


PB_BIND(rscp_RoverStatus, rscp_RoverStatus, AUTO)


PB_BIND(rscp_ResponseEnvelope, rscp_ResponseEnvelope, AUTO)





#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

